tests = [ {'description': 'Running',
	'steps': [ {'inputs': [('PINA', 0x00)],'iterations': 1}], # No actual input
	'expected': [('PORTB', 0x01)],
	},
	{'description': 'Running',
	'steps': [ {'inputs': [('PINA', 0x00)],'iterations': 1}], # No actual input
	'expected': [('PORTB', 0x02)],
	},
	{'description': 'Running',
	'steps': [ {'inputs': [('PINA', 0x00)],'iterations': 1}], # No actual input
	'expected': [('PORTB', 0x04)],
	},
	{'description': 'Running',
	'steps': [ {'inputs': [('PINA', 0x00)],'iterations': 1}], # No actual input
	'expected': [('PORTB', 0x02)],
	},
	{'description': 'Button',
	'steps': [ {'inputs': [('PINA', 0x01)],'iterations': 5}], 
	'expected': [('PORTB', 0x02)],
	},
	{'description': 'Button Release',
	'steps': [ {'inputs': [('PINA', 0x00)],'iterations': 10}], 
	'expected': [('PORTB', 0x02)],
	},
	{'description': 'Button Reset',
	'steps': [ {'inputs': [('PINA', 0x01)],'iterations': 1}], 
	'expected': [('PORTB', 0x01)],
	},
	{'description': 'Button Reset HOLD',
	'steps': [ {'inputs': [('PINA', 0x01)],'iterations': 1}], 
	'expected': [('PORTB', 0x02)],
	},
	{'description': 'Button Reset HOLD',
	'steps': [ {'inputs': [('PINA', 0x01)],'iterations': 1}], 
	'expected': [('PORTB', 0x04)],
	},
	{'description': 'Button Reset HOLD',
	'steps': [ {'inputs': [('PINA', 0x01)],'iterations': 1}], 
	'expected': [('PORTB', 0x02)],
	},
	{'description': 'Button Reset HOLD',
	'steps': [ {'inputs': [('PINA', 0x01)],'iterations': 1}], 
	'expected': [('PORTB', 0x01)],
	},
	{'description': 'Running and Button Reset Release',
	'steps': [ {'inputs': [('PINA', 0x00)],'iterations': 1}],
	'expected': [('PORTB', 0x02)],
	},
	{'description': 'Running',
	'steps': [ {'inputs': [('PINA', 0x00)],'iterations': 1}], # No actual input
	'expected': [('PORTB', 0x04)],
	},
	{'description': 'Running',
	'steps': [ {'inputs': [('PINA', 0x00)],'iterations': 1}], # No actual input
	'expected': [('PORTB', 0x02)],
	},
	{'description': 'Running',
	'steps': [ {'inputs': [('PINA', 0x00)],'iterations': 1}], # No actual input
	'expected': [('PORTB', 0x01)],
	},
    ]
watch = ['PORTB', 'L_STATE']

